version: "3.1"

services:
  # 对象存储服务
  oss:
    image: docker.io/minio/minio
    container_name: oss_minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "admin123"
      TZ: Asia/Shanghai
    command: server --console-address ':9001' /data
    privileged: true
    volumes:
      - ~/dl/dt/minio_data:/data

  # nginx
  nginx:
    image: docker.io/nginx
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ~/dl/dt/nginx_html:/usr/share/nginx/html
     # - ~/dl/dt/nginx_conf.d/:/etc/nginx/conf.d
    restart: always
    environment:
      TZ: Asia/Shanghai

